= Activitat: Modificació de dades
:doctype: article
:encoding: utf-8
:lang: ca
:toc: left
:toclevels: 3
:numbered:
:ascii-ids:

== Base de datos

Schema_HR y crear la siguiente tabla.
[source,sql]
----
CREATE TABLE MY_EMPLOYEE(
ID NUMERIC(4),
LAST_NAME VARCHAR(25),
FIRST_NAME VARCHAR(25),
USERID VARCHAR(8),
SALARY NUMERIC(9,2),
CONSTRAINT MY_EMPLOYEE_ID_PK PRIMARY KEY(ID));
----

1.	Cree un script para agregar la primera y la segunda fila de datos a MY_EMPLOYEE teniendo en cuenta los siguientes datos.


[source,sql]
----
> desc Hotels;
+-----+-----------------------+------------+-----------+------+
| ID  | LAST_NAME   -         | FIRST_NAME | USERID   | SALARY|
+-----+-----------------------+------------+-----------+------+
| 1   | Patel                 | Ralph      | rpatel   |    895|
+-----+-----------------------+------------+-----------+------+
| 2   | Dancs                 | Betty      | bdancs   |    860|
+-----+-----------------------+------------+-----------+------+
| 3   | Biri                  | Ben        | bbiri    |   1100|
+-----+-----------------------+------------+-----------+------+
| 4   | Newman                | Chad       | cnewman  |    750|
+-----+-----------------------+------------+-----------+------+
| 5   | Ropeburn              | Audrey     | aropebur |   1550|
+-----+-----------------------+------------+-----------+------+
----



2. Cree un script para insertar los usuarios con id 3 y 4 sin el userid y después actualizar el campo userid de los usuarios con los id 3 y 4. Tenga en cuenta que el ID de usuario debe ser la primera letra del nombre con los primeros siete caracteres del apellido.

3. Forzar que los datos introducidos sean permanentes en la base de datos y comprobar que los cuatro registros de la tabla se han añadido.

4. Cambie el apellido del empleado 3 a Drexler.

5. Cambie el salario a 1000 para todos los empleados con un salario inferior a 900.

6. Retire a Betty Dancs de la tabla.

7. Verifique los datos modificados en el MY_EMPLOYEE.

8. Forzar que los datos introducidos sean permanentes en la base de datos.

9. Cree un script para insertar el último registro de la tabla (consulte el ejercicio de tabla 1).

10. Verifique los datos modificados en el MY_EMPLOYEE.

11. Ponga una marca de la transacción en este momento llamada MARCA14

12. Vacíe la tabla y compruebe que está vacía, consultando los datos de la tabla.

13. Deshacer la operación DELETE que se acaba de realizar en el ejercicio 12 y, por lo tanto, debe mantenerse el INSERT anterior.

14. Confirme que la tabla está de vuelta como en el ejercicio 10 y guarde los cambios.
